blog/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    
    url(r'^admin/', include(admin.site.urls)),   
    
    url(r'^', include('core.urls', namespace="core")),

)

core/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url

from core import views, forms

urlpatterns = patterns('',
    
    url(r'^$', views.main, name='main'),
    url(r'^search', views.search, name='search'),
    
    url(r'^register', forms.RegistrationForm.as_view(), name='register'),
    url(r'^login', forms.LoginForm.as_view(), name='login'),
    url(r'^logout', views.logout, name='logout'),
    url(r'^profile$', views.profile_redirect, name='profile_redirect'),
    url(r'^profile/(?P<username>.+)$', views.profile, name='profile'),
    
    url(r'^detailed/id(?P<post_id>\d+)$', views.detailed, name='detailed'),
    
    url(r'^new$', views.new_redirect, name='new_redirect'),
    url(r'^new/(?P<username>.+)$', views.new_post, name='new_post'),
     
)

    

core/models.py
from django.db import models
from django.core.exceptions import ValidationError, ObjectDoesNotExist
import re
from django.db.models.fields.files import ImageField

def validate_text(value):
    pattern = re.compile("^[\w\s\d\,\.\!\-\~\?\+\'\"\:\/]{3,}$", flags=re.UNICODE)
    if not pattern.match(value):
        raise ValidationError("Some characters in text are not allowed. Or text is too short.")
    
    return value
 
#without tabs and new lines 
def validate_theme(value):
    pattern = re.compile("^[\w \d\,\.\!\-\~\?\+\'\":]{3,60}$", flags=re.UNICODE)
    if not pattern.match(value):
        raise ValidationError("Theme contains characters which are not allowed. Or text is too short.")
    try:
        Post.objects.get(theme=value)
        raise ValidationError("Theme '%s' already exists", value)
    except ObjectDoesNotExist:
        pass
    
    return value
    
def validate_user(value):
    pattern = re.compile("^[\w\d]{3,12}$", flags=re.UNICODE)
    if not pattern.match(value):
        raise ValidationError("Username is invalid. Only letters and digits, from 3 to 12 characters")
    
    return value
    
class Post(models.Model):
    text = models.CharField(max_length = 5000, validators=[validate_text])
    theme = models.CharField(max_length = 40, validators=[validate_theme])
    date = models.DateTimeField(auto_now = True)
    image = ImageField()
    user = models.CharField(max_length = 50)
    
    def __unicode__(self):
        return unicode(self.theme)

    
class Comment(models.Model):
    text = models.CharField(max_length = 100, validators=[validate_text])
    user = models.CharField(max_length = 20, validators=[validate_user])
    date = models.DateTimeField(auto_now = True)
    post = models.ForeignKey(Post)
    
    def __unicode__(self):
        return unicode(self.text)
    
    

core/forms.py
from django.views.generic.edit import FormView
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm
from core.models import Post, Comment
from django.forms.widgets import Textarea, TextInput
from django.forms.fields import ImageField, CharField


class PostForm(ModelForm):
    
    image = ImageField(required=False)
    user = CharField(required=False) 
    
    class Meta:
        model = Post
        fields = ('theme', 'text', 'image')
        exclude = ('user',)
        widgets = {
            'theme': TextInput(attrs={'size': '70'}),
            'text': Textarea(attrs={'style':'width:700px;height:400px;resize:none;'}),
        }
        
class CommentForm(ModelForm):
           
    class Meta:
        model = Comment
        fields = ('user', 'text')
        exclude = ('post',)
        widgets = {
            'user': TextInput(attrs={'size': '20'}),
            'text': Textarea(attrs={'style':'width:700px;height:80px;resize:none;'}),
        }
       
        
class RegistrationForm(FormView):
    
    form_class = UserCreationForm 
        
    success_url = '/login'
 
    template_name = 'core/register.html'
    
    def form_valid(self, form):
        
        form.save()
      
        return super(RegistrationForm, self).form_valid(form)


class LoginForm(FormView):
    form_class = AuthenticationForm
    
    success_url = '/profile'
    
    template_name = 'core/login.html'

    def form_valid(self, form):
        
        self.user = form.get_user()
        
        login(self.request, self.user)
        
        return super(LoginForm, self).form_valid(form)
    

core/views.py
from django.http import HttpResponseRedirect
from core.models import Post, Comment
from django.shortcuts import render, get_object_or_404

from django.contrib import auth
from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse
from cryptography.exceptions import InvalidKey
from datetime import datetime

from core.helpers import break_on_pages, ReturningRedirect, sort
from django.contrib.auth.decorators import login_required
from core.forms import PostForm, CommentForm
from django.contrib.auth.models import User


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('core:main'))

@login_required    
def profile_redirect(request):
    return HttpResponseRedirect(reverse('core:profile', kwargs={'username': request.user.username}))
    
@login_required    
def profile(request, username):
    
    user = get_object_or_404(User, username=username)
    
    posts = Post.objects.filter(user=username) 
    
    if request.method == 'GET' and request.user.username == username:
        try:
           
            context = break_on_pages(posts, request)
               
        except ReturningRedirect, e:
            return e.redirect

        form = PostForm()
        context.update({'form':form})

        return render(request, 'core/profile.html', context)
   
 
@login_required    
def new_redirect(request):
    return HttpResponseRedirect(reverse('core:new_post', kwargs={'username': request.user.username}))
 
 
@login_required 
def new_post(request, username):
      
    if request.method == 'GET' and request.user.username == username:
        
        form = PostForm()
        context = {'form':form}
        return render(request, 'core/new.html', context)
    
    elif request.method == 'POST' and request.user.username == username:
       
        form = PostForm(request.POST, request.FILES)
        
        if form.is_valid():
            post = form.save(commit=False)
            post.user = username
            post.save()      
            return HttpResponseRedirect(reverse('core:profile', kwargs={'username': request.user.username}))
        
        else:
            context = {'form' : form}
            return render(request, 'core/new.html', context)


def search(request):
    
    if request.method == 'POST':                
        query_value = str(request.POST.get('query'))
        
        if not query_value:
            return HttpResponseRedirect(reverse('core:main'))
            
        match_value = str(request.POST.get('match'))
        from_value = str(request.POST.get('date_from'))
        to_value = str(request.POST.get('date_to'))
        sort_value = str(request.POST.get('sort'))
        
        param_tupple = (query_value, match_value, from_value, to_value, sort_value) 
        
        url = reverse('core:search') + '?query=%s&match=%s&date_from=%s&date_to=%s&sort=%s' % param_tupple
        
        return HttpResponseRedirect(url)
    
    elif request.method == 'GET':
        
        query_value = unicode(request.GET.get('query'))
        
        if not query_value:
            return HttpResponseRedirect(reverse('core:main'))
        
        match_value = unicode(request.GET.get('match'))
        from_value = unicode(request.GET.get('date_from'))
        to_value = unicode(request.GET.get('date_to'))
        sort_value = unicode(request.GET.get('sort'))
        
        if(match_value == 'theme'):
            posts = Post.objects.filter(theme__regex=query_value)
        
        elif(match_value == 'text'):
            posts = Post.objects.filter(text__regex=query_value)
    
        elif(match_value == 'user'):
            posts = Post.objects.filter(user__regex=query_value)
    
        else:
            raise InvalidKey(unicode('invalid parameter ') + match_value)
        
        if from_value:
            from_date = datetime.strptime(from_value, '%d.%m.%Y')
            posts = posts.filter(date__gte=from_date)
    
        if to_value:
            to_date = datetime.strptime(to_value, '%d.%m.%Y')
            posts = posts.filter(date__lte=to_date)
                  
        sorted_posts = sort(posts, sort_value)
        
        try:
                 
            context = break_on_pages(sorted_posts, request)            
            return render(request, 'core/main.html', context)
        
        except ReturningRedirect, e:
            return e.redirect    
    

def main(request):
    
    posts = Post.objects.all()
    try:
        context = break_on_pages(posts, request)
        return render(request, 'core/main.html', context)
       
    except ReturningRedirect, e:
        return e.redirect   
    
       
def detailed(request, post_id): 
    
    post = get_object_or_404(Post, id=post_id)
    comments = post.comment_set.all()
    form = CommentForm()
    
    context = {'post' : post, 'form' : form, 'comments' : comments}
    
    if request.method == 'GET':                          
            
        return render(request, 'core/detailed.html', context)
    
    else:
                
        form = CommentForm(request.POST)      
        
        if form.is_valid():
  
            comment = form.save(commit=False)
    
            post = Post.objects.get(id=post_id)
            comment.post = post
            comment.save()
            return HttpResponseRedirect(reverse('core:detailed', kwargs={'post_id': post_id}))
        
        else:
            context.update({'form' : form})  
            return render(request, 'core/detailed.html', context) 
            
    

templates/core/detailed.html
<!DOCTYPE html>
<html>
<head>
{% load staticfiles %}
<meta charset="UTF-8">
<link rel="stylesheet" type="text/css" href="{% static 'core/main.css' %}">
<script src="{% static 'core/main.js' %}" type="text/javascript"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<title>{{ post.theme }}</title>
</head>
<body style="background-image: url(&quot;{% static 'core/background.jpg' %}&quot;);">

		{% if post.image %}
			<img class="image" alt="image" src="/{{ post.image.url }}"/>
		{% endif %}
		
	<div class="post detailed">
	
		<div class="title">{{ post.theme }}</div>
				
		<div class="text" type="text">{{ post.text }}</div>
		
		<hr>
		
		<div class="title comments">Comment:</div>
		
		<div class="center">
		<form action = "{% url 'core:detailed' post.id %}" method = "post" align="bottom">
		{% csrf_token %}
		<table class="TableWithBorder">
			<col width="90px"/>
			<col width="80px"/>
			<col width="50px"/>
			<col width="420px"/>
			<tr>
				<td align="center"><span>Name:</span></td>
				<td align="center">{{ form.user }}</td>
				<td><input type="submit" value="Submit"></td>
				<td></td>
			</tr>
			
			<tr>
				<td align="center" colspan="4"><span class="error">{% for error in form.user.errors %}
				{{ error }}
				{% endfor %}
				</span></td>
			</tr>
				
			<tr>
				<td align="center"><span>Text:</span></td>
				<td align="center" colspan="3">{{ form.text }}</td>
			</tr>
			
			<tr>
				<td align="center" colspan="4"><span class="error">{% for error in form.text.errors %}
				{{ error }}
				{% endfor %}
				</span></td>
			</tr>
								
		</table>
		</form>
		</div>
				
	</div>
	
	{% if comments %}
	{% for comment in comments %}
	<div class="post comment">
	
		<div class="comment_top">
			<div class="comment_top left">{{ comment.user }}</div>
			<div class="comment_top right">{{ comment.date|date:"d.m.o" }}</div>
		</div>
			
						
		<div class="text comment">{{ comment.text }}</div>
					
	</div>
	{% endfor %}
	{% endif %}
			
</body>
</html>

templates/core/login.html
<!DOCTYPE html>
<html>
<head>
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'core/register.css' %}">
<meta charset="UTF-8">
<title>Login</title>
</head>
<body style="background-image: url(&quot;{% static 'core/background.jpg' %}&quot;);">

	<div class="container">
	
	<div class="spacer left"></div>
		
	<div class="spacer right"></div>
			
	<div calss="spacer middle">
		<form action="{% url 'core:login' %}" method="post">
	{% csrf_token %}
	
		<table frame="border" bgcolor="#FFFFFF" style="border-collapse: collapse; border: 3px solid black;">
			<col width="90px"/>
			<col width="200px"/>
			
			<tr>
				<td align="center" colspan="2"><span style="font-weight: 700; font-size: 36px;">Login</span></td>
			</tr>
			
			<tr>
				<td align="center"><span>Username:</span></td>
				<td align="center">{{ form.username }}</td>
			</tr>
			
			<tr>
				<td align="center" colspan="2"><span class="error">{% for error in form.username.errors %}
				{{ error }}
				{% endfor %}
				</span></td>
			</tr>
			
			<tr>
				<td align="center"><span>Password:</span></td>
				<td align="center">{{ form.password }}</td>
			</tr>
			
			<tr>
				<td align="center" colspan="2"><span class="error">{% for error in form.password.errors %}
				{{ error }}
				{% endfor %}
				</span></td>
			</tr>
						
			<tr>
				<td align="center"><input type="submit" value="Login"/></td>
			</tr>
			
		</table>
	</form>
	</div>
	
	</div>
 	
</body>
</html>

templates/core/main.html
<!DOCTYPE html>
<html>
<head>
{% load staticfiles %}
<meta charset="UTF-8">
<title>SimpleBlogs</title>
<link rel="stylesheet" type="text/css" href="{% static 'core/main.css' %}">
<script src="{% static 'core/main.js' %}" type="text/javascript"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</head>
<body style="background-image: url(&quot;{% static 'core/background.jpg' %}&quot;);">

	<div class="pannel">
	
		<div class="spacer left"></div>
	
		<div class="button">
			<div class="button_body" id="search">Search</div>
		</div>
		
		<div class="button">
			<div id="logo" class="button_body logo">SimpleBlogs</div>
		</div>
		
		{% if user.is_authenticated %}
		<div class="button">
			<div class="button_body" id="profile">Profile</div>
		</div>
		
		<div class="button">
			<div class="button_body last" id="logout">Logout</div>
		</div>
	
		{% else %}
		<div class="button">
			<div class="button_body" id="register">Register</div>
		</div>
				
		<div class="button">
			<div class="button_body last" id="login">Login</div>
		</div>
			
		{% endif %}

		<div class="spacer right"></div>
		
	</div>
	
	<div id="searchForm">
	<center>
	<form action="{% url 'core:search' %}" method="post">
	{% csrf_token %}
	
		<table frame="border" bgcolor="#FFFFFF" style="border-collapse: collapse; border: 3px solid black;">
			<col width="90px"/>
			<col width="280px"/>
			<col width="120px"/>
			<tr>
				<td align="center" colspan="2"><input name="query" size="35" type="text"></td>
				
				<td align="center"><input type="submit" value="Search"/></td>
			</tr>
				
			<tr>
				<td align="center"><span>Match:</span></td>
				
				<td align="center"><span>Posted between:</span></td>
				
				<td align="center"><span>Sort:</span></td>
			</tr>
						
			<tr>
				<td align="center">
					Theme<input type="radio" name="match" value="theme" checked="checked"/>
				</td>
				
				<td align="center">
					<span>From: </span>
					<input type="date" name="date_from" size="7">
					<span style="padding-left: 5px;">(dd.mm.yyyy)</span>
				</td>
				
				<td align="center">
					<span style="padding-right: 50px;">Date</span><input type="radio" name="sort" value="date" checked="checked"/>
				</td>
			</tr>
			
			<tr>
				<td align="center">
					<span style="padding-right: 20px;">Text</span><input type="radio" name="match" value="text"/>
				</td>
				
				<td></td><!-- Empty cell -->
				
				<td align="center">
					Comments<input type="radio" name="sort" value="comments"/>
				</td>
			</tr>
			
			<tr>
				<td align="center">
					<span>Author</span><input type="radio" name="match" value="user"/>
				</td>
				
				<td align="center">
					<span style="padding-right: 25px;">To: </span>
					<input type="date" name="date_to" size="7">
					<span style="padding-left: 5px;">(dd.mm.yyyy)</span>
				</td>
				
				<td align="center">
					Unordered<input type="radio" name="sort" value="nosort"/>
				</td>
			</tr>
		</table>
	</form>
	</center>
	</div>
		
	{%for post in posts%}
		
	<div class="post">
	
		<a class="theme" href="/detailed/id{{ post.id }}" style="display: block">{{ post.theme }}</a>
		
		{% if post.image %}
			<img class="image" alt="image" src="{{ post.image.url }}"/>
		{% endif %}
				
		<div class="text" type="text">{{ post.text }}</div>
		
		<div class="postBottom">
			<div class="postBottom date">{{ post.date|date:"d.m.o" }}</div>
		
			<div class="postBottom comments">Comments: {{ post.comment_set.count }}</div>
			
			<div class="postBottom user">Author: {{ post.user }}</div>
		</div>
		
	</div>
	
	{%endfor%}
	
	
	{% if posts.has_other_pages %}	
	<div class="pager">
	
		{% if previous_page_url %}
		<a href="{{ previous_page_url }}" style="display:block;" class="page">	
			<img alt="back" src="{% static 'core/back_notactive.png' %}">
		</a>
		{% endif %}
	 	 	
	 	{% for page_number in posts.paginator.page_range %}
		
			{% if page_number == posts.number %} 
				<div class="page active">{{ page_number }}</div>
						
			{# first page #}
			{% elif page_number == 1 %}
				<a class="page" href="{{ first_page_url }}">{{ page_number }}</a>
			
			{# last page #}
			{% elif page_number == posts.paginator.num_pages %}
				<a class="page" href="{{ last_page_url }}">{{ page_number }}</a>
				
			{% elif page_number > 1 and page_number == posts.previous_page_number %}
				<div class="page">...</div>
				
			{% elif page_number < posts.paginator.num_pages and page_number == posts.next_page_number %}
				<div class="page">...</div>
							
			{% endif%}

			
		{% endfor %}
		
		{% if next_page_url %}
		<a href="{{ next_page_url }}" style="display:block;" class="page">	
			<img alt="forward" src="{% static 'core/forwd_notactive.png' %}">
		</a>
		{% endif %}
		
	</div>
	{% endif %}
	
	 
</body> 
</html>

templates/core/new.html
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
{% load staticfiles %}
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link rel="stylesheet" type="text/css" href="{% static 'core/new.css' %}">
<title>New Post</title>
</head>
<body style="background-image: url(&quot;{% static 'core/background.jpg' %}&quot;);">
	
	<div class="container">
	
	<div class="spacer left"></div>
		
	<div class="spacer right"></div>

	<div class="spacer middle">
	<form action="{{ request.path }}" method="post" enctype="multipart/form-data">
	{% csrf_token %}
		<table frame="border" bgcolor="#FFFFFF" style="border-collapse: collapse; border: 3px solid black;">
			<col width="90px"/>
			<col width="200px"/>
			<col width="40px"/>
			
			<tr>
				<td align="center" colspan="3"><span style="font-weight: 700; font-size: 36px;">New Post</span></td>
			</tr>
			
			<tr>
				<td align="center"><span>Theme:</span></td>
				<td align="center" colspan="2">{{ form.theme }}</td>
			</tr>
			
			<tr>
				<td align="center" colspan="3"><span class="error">{% for error in form.theme.errors %}
				{{ error }}
				{% endfor %}
				</span></td>
			</tr>
			
			<tr>
				<td align="center"><span>Text:</span></td>
				<td align="center" colspan="2">{{ form.text }}</td>
			</tr>
			
			<tr>
				<td align="center" colspan="3"><span class="error">{% for error in form.text.errors %}
				{{ error }}
				{% endfor %}
				</span></td>
			</tr>
			
			<tr>
				<td align="center"><span>Image:</span></td>
				<td align="center">{{ form.image }}</td>
				<td><input type="submit" value="Post"></td>
			</tr>

		</table>	
	</form>
	</div>	
	
	</div>	
</body>
</html>

templates/core/profile.html
<!DOCTYPE html>
<html>
<head>
{% load staticfiles %}
<meta charset="UTF-8">
<title>Profile</title>
<link rel="stylesheet" type="text/css" href="{% static 'core/main.css' %}">
<script src="{% static 'core/main.js' %}" type="text/javascript"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</head>
<body style="background-image: url(&quot;{% static 'core/background.jpg' %}&quot;);">

	<div class="pannel">
	
		<div class="spacer left"></div>
		<div class="button">
			<div class="button_body" id="new">New</div>
		</div>
		
		<div class="button">
			<div class="button_body logo" id="logo">SimpleBlogs</div>
		</div>
				
		<div class="button">
			<div class="button_body" id="logout">Logout</div>
		</div>
		
		<div class="spacer right"></div>
		
	</div>
			
	{%for post in posts%}
		
	<div class="post">
	
		<a class="theme" href="/detailed/id{{ post.id }}" style="display: block">{{ post.theme }}</a>
		
		{% if post.image %}
			<img class="image" alt="image" src="/{{ post.image.url }}"/>
		{% endif %}
						
		<div class="text" type="text">{{ post.text }}</div>
		
		<div class="postBottom">
			<div class="postBottom date">{{ post.date|date:"d.m.o" }}</div>
		
			<div class="postBottom comments">Comments: {{ post.comment_set.count }}</div>
		</div>
		
	</div>
	
	{%endfor%}
	
	
	{% if posts.has_other_pages %}	
	<div class="pager">
	
		{% if previous_page_url %}
		<a href="{{ previous_page_url }}" style="display:block;" class="page">	
			<img alt="back" src="{% static 'core/back_notactive.png' %}">
		</a>
		{% endif %}
	 	 	
	 	{% for page_number in posts.paginator.page_range %}
		
			{% if page_number == posts.number %} 
				<div class="page active">{{ page_number }}</div>
						
			{# first page #}
			{% elif page_number == 1 %}
				<a class="page" href="{{ first_page_url }}">{{ page_number }}</a>
			
			{# last page #}
			{% elif page_number == posts.paginator.num_pages %}
				<a class="page" href="{{ last_page_url }}">{{ page_number }}</a>
				
			{% elif page_number > 1 and page_number == posts.previous_page_number %}
				<div class="page">...</div>
				
			{% elif page_number < posts.paginator.num_pages and page_number == posts.next_page_number %}
				<div class="page">...</div>
							
			{% endif%}

			
		{% endfor %}
		
		{% if next_page_url %}
		<a href="{{ next_page_url }}" style="display:block;" class="page">	
			<img alt="forward" src="{% static 'core/forwd_notactive.png' %}">
		</a>
		{% endif %}
		
	</div>
	{% endif %}
	
</body> 
</html>

templates/core/register.html
<!DOCTYPE html>
<html>
<head>
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'core/register.css' %}">
<meta charset="UTF-8">
<title>Register</title>
</head>
<body style="background-image: url(&quot;{% static 'core/background.jpg' %}&quot;);">

	<div class="container">
	
	<div class="spacer left"></div>
		
	<div class="spacer right"></div>
			
	<div calss="spacer middle">
		<form action="{% url 'core:register' %}" method="post">
	{% csrf_token %}
	
		<table frame="border" bgcolor="#FFFFFF" style="border-collapse: collapse; border: 3px solid black;">
			<col width="90px"/>
			<col width="200px"/>
			
			<tr>
				<td align="center" colspan="2"><span style="font-weight: 700; font-size: 36px;">Register</span></td>
			</tr>
			
			<tr>
				<td align="center"><span>Username:</span></td>
				<td align="center">{{ form.username }}</td>
			</tr>
			
			<tr>
				<td align="center" colspan="2"><span class="error">{% for error in form.username.errors %}
				{{ error }}
				{% endfor %}
				</span></td>
			</tr>
			
			<tr>
				<td align="center"><span>Password:</span></td>
				<td align="center">{{ form.password1 }}</td>
			</tr>
			
			<tr>
				<td align="center" colspan="2"><span class="error">{% for error in form.password1.errors %}
				{{ error }}
				{% endfor %}
				</span></td>
			</tr>
			
			<tr>
				<td align="center"><span>Confirm:</span></td>
				<td align="center">{{ form.password2 }}</td>
			</tr>
			
			<tr>
				<td align="center" colspan="2"><span class="error">{% for error in form.password2.errors %}
				{{ error }}
				{% endfor %}
				</span></td>
			</tr>
			
			<tr>
				<td align="center"><input type="submit" value="Register"/></td>
			</tr>
			
		</table>
	</form>
	</div>
	
	</div>
 		
</body>
</html>